service: nuxt-app

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: 'ap-southeast-1'
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${opt:stage, 'production'}
  apiGateway:
    shouldStartNameWithService: true

functions:
  nuxt:
    handler: nuxtHandler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  apigwBinary:
    types:
      - '*/*'
  serverless-offline:
    noPrependStageInUrl: true

package:
  excludeDevDependencies: true
